### PR TITLE
Branch protection

### PR DESCRIPTION
**Pull request by bhufmann**
- Update branch protection rules for main source repo
- Add topics to trace compass incubator main repo

Signed-off-by: Bernd Hufmann <bernd.hufmann@ericsson.com>

### CODE REVIEW

**Comment by mbarbero** [comment]
Please fix the unsupported topic 'trace compass' (no space allowed in there)

**Comment by bhufmann** [comment]
@mbarbero I'm not clear why the otterdog-sync fails. Could you please let me know how to fix it? Thanks

**Comment by netomi** [comment]
It means that the configuration is Out of sync with the live setting and when we Merge this PR these setting will be changed.

**Comment by netomi** [comment]
It means that the configuration is out of sync with the live settings and when we merge this PR these settings will be changed. Normally we fix the config to reflect the live settings but in this case i would just Bypass and Merge as the default should anyways be read permissions.

**Review by mbarbero — APPROVED** [review]

**Comment by mbarbero** [comment]
Sorry for the noise.

**Pull request merged**
