### PR TITLE
Set allow_merge_commit to false

### PR DESCRIPTION
**Pull request by bhufmann**
Signed-off-by: Bernd Hufmann <bernd.hufmann@ericsson.com>

### CODE REVIEW

**Review by MatthewKhouzam — APPROVED** [review]
YES!

**Review by PatrickTasse — APPROVED** [review]

**Comment by netomi** [comment]
just fyi: allow_merge_commit is already set to false in the default config, so you dont have to explicitly set it to true, but you can also remove the setting altogether to achieve the same, keeps the configuration minimal.

In order to more easily play with the configuration, you can use the playground at

https://eclipse-tracecompass-incubator.github.io/.eclipsefdn/playground/

it exists for any project separately atm, but we plan to include that in the dashboard as well

**Comment by PatrickTasse** [comment]
@netomi The initial commit of the .jsonnet file from otterdog overrides allow_merge_commit to true, do you know where that comes from?

**Comment by netomi** [comment]
that was the result of the initial import operation where the current live configuration is taken as is and the jsonnet file is created by diffing the current config to the default config. So any setting that differs from the default config is visible in your jsonnet file directly, the rest is inherited.

**Pull request merged**
